id: A340AA1C9
title: Rays of Moonlight to Dispel the Darkness of Misdeeds
type: translation
pechas:
- I9D41411D
- I033D6C46
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:57:53.879506
  last_modified_at: 2023-01-04 12:57:53.879529
  collections:
  - Lobzang Chökyi Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  I9D41411D/8400: '2545'
  I033D6C46/4DFC: '2545'
